### PR TITLE
SKN-492 add logic to create campaigns during edit

### PR DESCRIPTION
**Pull request by PedroLabrador**

### CODE REVIEW

**Review by maacaro — CHANGES_REQUESTED** [review]
@PedroLabrador  no test at all ?

**Comment by PedroLabrador** [comment]
> @PedroLabrador no test at all ?

es verdad, es que como los habia hecho ayer para el create, no pense para el update

**Review by maacaro — CHANGES_REQUESTED** [review]
@PedroLabrador needs work!! we should at least test that the function for create either amazon or facebook campaign and adset are called the exact amount of time with rigth data when either the request contains either new Facebook campaigns or Facebook Addset or the request contains either new Amazon campaigns or Amazon Addset,

**Comment by PedroLabrador** [comment]
> @PedroLabrador needs work!! we should at least test that the function for create either amazon or facebook campaign and adset are called the exact amount of time with rigth data when either the request contains either new Facebook campaigns or Facebook Addset or the request contains either new Amazon campaigns or Amazon Addset,

listo los tests

**Pull request merged**
